# Generated by Django 5.0.6 on 2024-06-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_order_cartitem_order_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=220),
            preserve_default=False,
        ),
    ]
