# Generated by Django 5.0.6 on 2024-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_description_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
