# Generated by Django 5.0.6 on 2024-07-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_confirmedorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedorder',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
