# Generated by Django 5.0.6 on 2024-07-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_confirmedorder_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedorder',
            name='confirmed',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
