# Generated by Django 5.0.6 on 2024-08-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_confirmedorder_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedorder',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='confirmedorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
