# Generated by Django 5.0.6 on 2024-08-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_confirmedorder_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedorder',
            name='status',
            field=models.CharField(default='something', max_length=10),
        ),
    ]
