# Generated by Django 5.0.6 on 2024-08-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_confirmedorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedorder',
            name='status',
            field=models.CharField(default='this and that', max_length=10),
        ),
    ]
