# Generated by Django 5.0.6 on 2024-08-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_newmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewModel',
        ),
        migrations.RemoveField(
            model_name='confirmedorder',
            name='status',
        ),
    ]
