# Generated by Django 5.0.6 on 2024-08-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_delete_newmodel_remove_confirmedorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedorder',
            name='pending_status',
            field=models.CharField(default='Pending', max_length=20),
            preserve_default=False,
        ),
    ]
