# Generated by Django 5.0.6 on 2024-08-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_confirmedorder_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
